permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Harrison Dekker
url: https://vagrantscholar.github.io/workshops
description: Ruminations of a vagrant scholar.
twitter: vagrantscholar
