permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: vagrant scholar
url: https://vagrantscholar.github.io/workshops
description: Ruminations of a vagrant scholar.
twitter: vagrantscholar
