permalink: /posts/:title
markdown: kramdown

gems:
  - jekyll-sitemap

name: Harrison Dekker
url: https://linkedin.com/in/hgdekker
description: Ruminations of a vagrant scholar.
twitter: vagrantscholar
